### PR TITLE
strip trailing slash in run/add_route instead of match

### PR DESCRIPTION
**Pull request by tamland**
fixes https://github.com/tamland/kodi-plugin-routing/pull/13#issuecomment-529076833
@dagwieers Thoughts?
cc @michaelarnauts

### CODE REVIEW

**Comment by dagwieers** [comment]
I was making a fix for this as well. But unsure what the expectation is for a route with trailing slash, should it then only match a single slash ?

```patch
diff --git a/lib/routing.py b/lib/routing.py
index 5d8c479..0785b55 100644
--- a/lib/routing.py
+++ b/lib/routing.py
@@ -160,13 +160,18 @@ class UrlRule:
         Check if path matches this rule. Returns a dictionary of the extracted
         arguments if match, otherwise None.
         """
-        # Strip trailing slashes
+        # match = self._regex.search(urlsplit(path).path)
+        match = self._regex.search(path)
+        if match:
+            return match.groupdict()
         if len(path) > 1:
+            # Strip trailing slashes
             path = path.rstrip('/')
+            match = self._regex.search(path)
+            if match:
+                return match.groupdict()
+        return None
 
-        # match = self._regex.search(urlsplit(path).path)
-        match = self._regex.search(path)
-        return match.groupdict() if match else None
 
     def make_path(self, *args, **kwargs):
         """Construct a path from arguments."""
diff --git a/lib/tests.py b/lib/tests.py
index 42ab874..b2b420a 100644
--- a/lib/tests.py
+++ b/lib/tests.py
@@ -120,3 +120,7 @@ def test_trailing_slashes():
     assert UrlRule("/p/<foo>").match("/p/bar/") == {'foo': 'bar'}
     assert UrlRule("/p/<foo>").match("/p/bar//") == {'foo': 'bar'}
     assert UrlRule("/p/<foo>").match("/p/bar///") == {'foo': 'bar'}
+    assert UrlRule("/p/<foo>/").match("/p/bar") is None
+    assert UrlRule("/p/<foo>/").match("/p/bar/") == {'foo': 'bar'}
+    assert UrlRule("/p/<foo>/").match("/p/bar//") is None
+    assert UrlRule("/p/<foo>/").match("/p/bar///") is None
```

**Comment by tamland** [comment]
I think we can, or at least should, be non-strict about `/` and say they are the same route by default no matter which is registered. That's the least surprising behavior imo. An url like `/p/bar//` doesn't usually make any sense anyway

**Comment by dagwieers** [comment]
@tamland IMO it should behave like URLs. Because it is a URL 😉

**Comment by michaelarnauts** [comment]
I think you need to strip them when you define a route, and also when you resolve a route. The root `/` is an exception.

**Comment by tamland** [comment]
@dagwieers This isn't routing patterns though, not URLs. From what i recall from working with routing in various frontend and backend frameworks, that's how most work; and you have to explicitly set it if you want something else.

**Comment by dagwieers** [comment]
Hmm, it seems as if this undid the changes we needed.

If we now have a route **/foo/bar** it will not be matched by **/foo/bar/**.
And if you have a route **/foo/bar/** it will not be matched by **/foo/bar/**.

Now it behaves like this, which IMO is wrong.
```python
def test_trailing_slashes():
    assert UrlRule("/p/<foo>").match("/p/bar") == {'foo': 'bar'}
    assert UrlRule("/p/<foo>").match("/p/bar/") is None
    assert UrlRule("/p/<foo>").match("/p/bar//")  is None
    assert UrlRule("/p/<foo>").match("/p/bar///") is None
    assert UrlRule("/p/<foo>/").match("/p/bar") == {'foo': 'bar'}
    assert UrlRule("/p/<foo>/").match("/p/bar/") is None
    assert UrlRule("/p/<foo>/").match("/p/bar//") is None
    assert UrlRule("/p/<foo>/").match("/p/bar///") is None
```

**Comment by dagwieers** [comment]
If this is how it is supposed to work, I guess we will have to strip the trailing slash ourselves before passing it to the routing module. I am disappointed.

```python
def run(argv):
    ''' Addon entry point from wrapper '''
    kodi.log_access(to_unicode(argv[0]))
    argv[0] = argv[0].rstrip('/') or '/'
    plugin.run(argv)
```

**Comment by tamland** [comment]
@dagwieers Please reread the code and formulate the issue properly. The url `/foo/bar/` will matched by both `/foo/bar` and `/foo/bar/` as you can see in the two tests. The `UrlRule.match` tests doesn't make any sense because trailing slash handling isn't done in that method.

**Comment by dagwieers** [comment]
@ŧamland Oh, I see. I would expect `match()` to do the stripping though. Sorry for the wrong conclusion.

**Pull request merged**
